### ISSUE TITLE
env报错

### ISSUE THREAD

**Issue by W1ndys** [Wcowin/Mkdocs-Wcowin#8]
我尝试给你Pull Request，把友链界面改成软编码，可以省去编码时间，但是报错了预料之外的错误，你有什么头绪吗，我猜测是插件或许有冲突
[link.zip](https://github.com/Wcowin/Mkdocs-Wcowin/files/14931993/link.zip)
```
ERROR   -  Error reading page 'blog/Mkdocs/mkdocs1.md': 'env' is undefined
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\W1ndys\anaconda3\Scripts\mkdocs.exe\__main__.py", line 7, in <module>
  File "C:\Users\W1ndys\anaconda3\Lib\site-packages\click\core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\W1ndys\anaconda3\Lib\site-packages\click\core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "C:\Users\W1ndys\anaconda3\Lib\site-packages\click\core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\W1ndys\anaconda3\Lib\site-packages\click\core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\W1ndys\anaconda3\Lib\site-packages\click\core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\W1ndys\anaconda3\Lib\site-packages\mkdocs\__main__.py", line 270, in serve_command
    serve.serve(**kwargs)
  File "C:\Users\W1ndys\anaconda3\Lib\site-packages\mkdocs\commands\serve.py", line 86, in serve
    builder(config)
  File "C:\Users\W1ndys\anaconda3\Lib\site-packages\mkdocs\commands\serve.py", line 67, in builder
    build(config, live_server=None if is_clean else server, dirty=is_dirty)
  File "C:\Users\W1ndys\anaconda3\Lib\site-packages\mkdocs\commands\build.py", line 322, in build
    _populate_page(file.page, config, files, dirty)
  File "C:\Users\W1ndys\anaconda3\Lib\site-packages\mkdocs\commands\build.py", line 171, in _populate_page
    page.markdown = config.plugins.on_page_markdown(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\W1ndys\anaconda3\Lib\site-packages\mkdocs\plugins.py", line 575, in on_page_markdown
    return self.run_event('page_markdown', markdown, page=page, config=config, files=files)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\W1ndys\anaconda3\Lib\site-packages\mkdocs\plugins.py", line 507, in run_event
    result = method(item, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\W1ndys\anaconda3\Lib\site-packages\markdownextradata\plugin.py", line 99, in on_page_markdown
    return self.apply_template(markdown)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\W1ndys\anaconda3\Lib\site-packages\markdownextradata\plugin.py", line 111, in apply_template
    return md_template.render({**self.mkdocsConfig, **self.mkdocsConfig.get("extra")})
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\W1ndys\anaconda3\Lib\site-packages\jinja2\environment.py", line 1301, in render
    self.environment.handle_exception()
  File "C:\Users\W1ndys\anaconda3\Lib\site-packages\jinja2\environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "<template>", line 115, in top-level template code
  File "C:\Users\W1ndys\anaconda3\Lib\site-packages\jinja2\environment.py", line 485, in getattr
    return getattr(obj, attribute)
           ^^^^^^^^^^^^^^^^^^^^^^^
jinja2.exceptions.UndefinedError: 'env' is undefined
```

**Comment by W1ndys** [comment]
嗯，我定位到问题了，是blog文件里面的软编码变量也触发到了文件配置，env的配置

**Comment by W1ndys** [comment]
我删去blog文件后，成功实现软编码添加友链
![image](https://github.com/Wcowin/Mkdocs-Wcowin/assets/109416673/c73b9b4b-099d-4704-a275-f6f4612fe55a)

如果你有更好的解决办法，欢迎交流

**Comment by Wcowin** [comment]
> 我删去blog文件后，成功实现软编码添加友链 ![image](https://private-user-images.githubusercontent.com/109416673/321234930-c73b9b4b-099d-4704-a275-f6f4612fe55a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI3OTgyMTIsIm5iZiI6MTcxMjc5NzkxMiwicGF0aCI6Ii8xMDk0MTY2NzMvMzIxMjM0OTMwLWM3M2I5YjRiLTA5OWQtNDcwNC1hMjc1LWY2ZjQ2MTJmZTU1YS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQxMVQwMTExNTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yOTEzM2I0NmJlOTQwOTcyMDcwNTMyNWE5MzJjNzBlMjI3ODI0Y2I5NWFjZTBiYzg2YmRjYTZkYTE2ZDY3NDg1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.5Hcc--PAFiCzk50GGOvFYUC9yjbaMCvviMW5K-e7QOE)
> 
> 如果你有更好的解决办法，欢迎交流

这个效果看起来不错！我想尝试一下，我看到link文件里多了一个link.yaml文件~我大概是看懂了
我对类似于` {% for friend in link.friends %}`、`{{ friend.name }}`的语句不太熟悉，但我看到MKdocs的overrides覆写多使用这种语句。
我的理解是：这个功能会把link.yml的信息类似于填坑的方式一一对应填充到link.md指定的信息里，如`{{ friend.name }}`

**Comment by Wcowin** [comment]
> 我去插件发布页看了一下，他好像停止更新2年左右了，估计是没法从插件上解决了

你是否了解MKdocs插件的开发呢？我一直想研究一下MKdocs文章字数统计的插件。除了[mkdlocs-statistics-plugin](https://github.com/TonyCrane/mkdocs-statistics-plugin),我在github上未找到类似的插件

**Comment by W1ndys** [comment]
这种方法可以实现不需要改动友链.md文件，也不需要重复书写HTML代码，只需要在link.yaml文件中直接添加下面内容即可

```yaml
- name: 昵称
  avatar: 头像
  link: 网站地址
  description: 描述
```


> 你是否了解MKdocs插件的开发呢？

不幸的是我不了解插件开发

我给Markdownextradata插件提交了issues，虽然插件三年没更新，但是插件作者已经回复我了，希望他能修复这个bug

如果bug不会被修复，且决定要采用软编码的办法代替友链添加的话
我能想到的方法是尽量避免在Markdown书写{{env.xxx}}这种语法，可以用一些描述性语言代替
比如：

```yaml
<<env.xxx>>.  # 注意这里需要把<>换成{}
```

如果你有更好的办法，欢迎交流

**Comment by W1ndys** [comment]
测试了好几遍我决定不再Pr了，如果改文件的话需要改动的太多了，这就不礼貌了。
要添加的内容我在刚开始的地方打包好了。
![image](https://github.com/Wcowin/Mkdocs-Wcowin/assets/109416673/225a527a-b1d1-4300-8abe-f8f31a5760b6)
如果还有其他需要交流，欢迎回复

**Comment by Wcowin** [comment]
<img width="929" alt="image" src="https://github.com/Wcowin/Mkdocs-Wcowin/assets/99159173/c41e9144-7724-488a-952c-2612bf496bc5">
W朋友，我合并了你的psh，并且在本地得到了实现，这是很好的工作！

**Comment by Wcowin** [comment]
<img width="873" alt="image" src="https://github.com/Wcowin/Mkdocs-Wcowin/assets/99159173/33239d06-99c3-4787-a6a8-17c31a627d10">

**Comment by Wcowin** [comment]
<img width="448" alt="image" src="https://github.com/Wcowin/Mkdocs-Wcowin/assets/99159173/6e5f5425-f98d-4090-9833-3af8dcf2bcad">
W~哈哈看来贡献者插件也起作用了，如果你有更好的想法，欢迎交流！邀请您共同维护这个MKdocs仓库！

**Comment by W1ndys** [comment]
> <img alt="image" width="873" src="https://private-user-images.githubusercontent.com/99159173/321715624-33239d06-99c3-4787-a6a8-17c31a627d10.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI4NTgwNjUsIm5iZiI6MTcxMjg1Nzc2NSwicGF0aCI6Ii85OTE1OTE3My8zMjE3MTU2MjQtMzMyMzlkMDYtOTljMy00Nzg3LWE2YTgtMTdjMzFhNjI3ZDEwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDExVDE3NDkyNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTMwNzdjYTFhY2VkYzcxMDQyODkyZTQ5MTRhYTQ5NjhiZGNlZGRiZjIyMjdiNTQzMDc3MmRlMDRmNjg4YTUxM2UmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.-6Yts1nH154K_uOL8N3oVZ3E080jldmpRZaTFZ7YW4o">

这个地方我还没有关注过，虽然我的本地也有很多警告的info信息，我一般都直接忽视了（因为他对实际页面并没有什么影响），也许我会在以后尝试解决warning的处理办法（目前学业繁忙暂时没有太多时间，我自己的Mkdocs站点计划是今年暑假重点施工）

**Comment by W1ndys** [comment]
> <img alt="image" width="448" src="https://private-user-images.githubusercontent.com/99159173/321718961-6e5f5425-f98d-4090-9833-3af8dcf2bcad.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI4NTgwNjUsIm5iZiI6MTcxMjg1Nzc2NSwicGF0aCI6Ii85OTE1OTE3My8zMjE3MTg5NjEtNmU1ZjU0MjUtZjk4ZC00MDkwLTk4MzMtM2FmOGRjZjJiY2FkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDExVDE3NDkyNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNkYmM3Mzk3YWQ5NDg3NmU4OGFkYTU3MGU1YzE3ZjdhODAzZDRjOGIzYjE3OTE2ZTI5YTg1MmE0YjY4ZGUyMzkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.foaz4Vr7btRRcMuRRLx2ggRcpdsdS-97seT17Cn8R30"> W~哈哈看来贡献者插件也起作用了，如果你有更好的想法，欢迎交流！邀请您共同维护这个MKdocs仓库！

我很喜欢你的美化教程，关于Mkdocs-material的美化教程本身就不多，这算是一股清流了

**Comment by Wcowin** [comment]
谢谢W！我会继续坚持更新最新的中文MKdocs教程，也同时欢迎你的交流建议~🤗常联系
